In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.float_format', lambda x: '%.2f' % x)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
df_ = pd.read_csv("/content/advertising.csv")
df = df_.copy()
df.head()

      TV  radio  newspaper  sales
0 230.10  37.80      69.20  22.10
1  44.50  39.30      45.10  10.40
2  17.20  45.90      69.30   9.30
3 151.50  41.30      58.50  18.50
4 180.80  10.80      58.40  12.90

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [6]:
df.describe().T

           count   mean   std  min   25%    50%    75%    max
TV        200.00 147.04 85.85 0.70 74.38 149.75 218.82 296.40
radio     200.00  23.26 14.85 0.00  9.97  22.90  36.52  49.60
newspaper 200.00  30.55 21.78 0.30 12.75  25.75  45.10 114.00
sales     200.00  14.02  5.22 1.60 10.38  12.90  17.40  27.00

## Model

In [8]:
X = df.drop('sales',axis=1)
y= df[['sales']]
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.25, random_state=20)
y_test.shape[0]

50

In [10]:
y_train.shape[0]

150

In [11]:
reg_model= LinearRegression().fit(X_train ,y_train)

In [12]:
# constant (b - bias)
reg_model.intercept_[0]

3.333378469114521

In [13]:
# coefficients (w - weights)
reg_model.coef_[0][0]

0.04327316510882865

## Prediction

In [16]:
#MSE Train
#Sales mean = 14.02
y_pred = reg_model.predict(X_train)
np.sqrt(mean_squared_error(y_train, y_pred))

1.4713574325314802

In [18]:
#MAE Train
np.sqrt(mean_absolute_error(y_train, y_pred))

1.0720626677551928

In [17]:
# R² Train
# R² is interpreted as follows:
# 1.0: The model explains the data perfectly.
# 0.0: The model explains the target variable as if it were a random guess.
reg_model.score(X_train, y_train)

0.9115679170982784

In [19]:
# MSE Test
y_pred  = reg_model.predict(X_test)
np.sqrt(mean_squared_error(y_pred, y_test))

2.2082252628863452

In [20]:
# MAE Test
np.sqrt(mean_absolute_error(y_test, y_pred))

1.214906301814145

In [21]:
# R² Test
reg_model.score(X_test, y_test)

0.8601993386354956

## Validation

In [22]:
# 10 Fold Cross Validation
np.mean(np.sqrt(-cross_val_score(reg_model,
                X,
                y,
                cv=10,
                scoring="neg_mean_squared_error")))

1.6913531708051797

In [23]:
reg_model.coef_

array([[ 0.04327317,  0.19283212, -0.00187001]])

In [26]:
# For example;
# TV spend = 70
# Radio spend = 40
# Newspaper spend = 30

data  =[[150], [40], [30]]
data = pd.DataFrame(data).T

reg_model.predict(data)[0][0] # Sales=17.48

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

17.481537702146063